apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:  #template que definen los contenedores
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "50Mi"  #maximo de memoria
              cpu: "2"        #maximo de cpu
            requests:
              memory: "25Mi"   #minimo de memoria que arranca
              cpu: "0.5"       #minimo de cpu que arranca
