apiVersion: v1
kind: Service
metadata:
  name: service-redis-master
  labels:
    app: redis
    role: master
spec:
  ports:
  - port: 6379
    targetPort: 6379
  type: ClusterIP
  selector:
    app: redis
    role: master