apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: app-php
spec:
  selector:
    matchLabels:
      app: app-php
  replicas: 1
  template:
    metadata:
      labels:
        app: app-php
    spec:
      containers:
        - name: php-redis
          image: gcr.io/google_samples/gb-frontend:v4
          env:
            - name: GET_HOSTS_FROM
              value: dns