apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany # Leida Y escrita por muchos
  persistentVolumeReclaimPolicy: Recycle #reutlizar
  storageClassName: wordpress
  hostPath:
    path: "/app/wordpress"
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
spec:
  storageClassName: wordpress
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi