apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deploy
  labels:
    app: wordpress
    estado: desarrollo
spec:
  selector:
    matchLabels:
      app: wordpress
      estado: desarrollo
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
        estado: desarrollo
    spec:
      containers:
        - name: wordpress
          image: wordpress
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: WORDPRESS_DB_HOST
              value: mysqldb
            - name: WORDPRESS_DB_PASSWORD
              value: admin
          ports:
            - containerPort: 80
          volumeMounts:
            - name: wordpress
              mountPath: /var/www/html
      volumes:
        - name: wordpress
          persistentVolumeClaim:
            claimName: wordpress-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-sv
  labels:
     estado: desarrollo
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    app: wordpress
    estado: desarrollo